### ISSUE TITLE
Redlure-Console.py Stops Responding

### ISSUE THREAD

**Issue by RackunSec** [redlure/redlure-console#10]
After a short period our server stops responding, but the UI still loads. Right click->Inspect Element shows that the server is "unreachable" and the UI states that with a red "x" Strace on the PID shows that the process is not responding.  Each time we restart the process in the screen session using pipenv, it works again but not for long enough to use the product. It eventually just stops responding without any error messages to the screen session. Any ideas?

**Comment by Tw1sm** [comment]
@RackunSec How much memory does the server running the console and client have? I believe this would happen on cheaper cloud deployments with minimal RAM.

If you've got 2+ GBs of memory on that server and the issue persists across reboots, I'm really not sure what would cause the Flask server to crash without any error messages.
